version: 0.2

env:
  git-credential-helper: yes
  variables:
    CGO_ENABLED: "0"
    GOOS: "linux"
    GOARCH: "amd64"
    PREFIX: ""

proxy:
  upload-artifacts: yes
  logs: yes

phases:
  install:
    runtime-versions:
      golang: 1.14

  build:
    commands: # requires AWS_ACCOUNT_ID env to be set
      - go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o fairy main.go
      - IMAGE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PREFIX}fairy:latest"
      - docker build -t "${IMAGE}" .
      - $(aws ecr get-login --no-email)
      - docker push "${IMAGE}"

cache:
  paths:
    - '/go/pkg/**/*'
